In [1]:
import numpy as np

In [4]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [6]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [7]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [8]:
np.where(a)

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)

In [9]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [10]:
A = np.array([[1, 2, np.nan, 4], [np.nan, 6, 7, 8], [10, np.nan, 12, 13], [14, 15, 16, 17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [12]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [17]:
b = np.where(np.isnan(A))
b

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [24]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1, 20).reshape(2, -1)
a,b

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))

In [25]:
np.vstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.hstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [27]:
#Kesişim

In [28]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [29]:
np.intersect1d(c1,c2)

array([20, 40, 60])

In [30]:
np.setdiff1d(c1,c2)

array([10, 30, 50])

In [31]:
a1 = np.arange(0,60)
a1[np.where(((a1>20)&(a1 < 35)|(a1 % 10 == 0)))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [32]:
#Reverse Array

In [33]:
a4 = np.arange(10, 30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [35]:
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [36]:
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [37]:
a3 = np.array([[3,2,8,1], [70,50,10,67], [45, 25, 75, 15], [12, 9, 77, 4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [38]:
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [39]:
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [40]:
a3[::-1,::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [41]:
#Sıralama

In [42]:
a = np.array([10, 5, 2, 22, 12, 92, 17, 33])
np.sort(a)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [43]:
a3 = np.array([[3,2,8,1], [70,50,10,67], [45, 25, 75, 15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [44]:
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [45]:
np.sort(a3, axis = 1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [46]:
np.sort(a3, axis = 0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [47]:
#Dosya yükleme & saklama

In [48]:
p7 = np.arange(10, 200, 11)
p7

array([ 10,  21,  32,  43,  54,  65,  76,  87,  98, 109, 120, 131, 142,
       153, 164, 175, 186, 197])

In [49]:
np.savetxt('testAI7.csv', p7, delimiter = ',')

In [50]:
p8 = np.arange(0, 121).reshape(11, 11)
p8

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [51]:
np.save('testAIGroup7.npy', p8)

In [52]:
p9 = np.load('testAIGroup7.npy')
p9

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [53]:
p11 = np.arange(0, 1000000).reshape(1000, 1000)
p11

array([[     0,      1,      2, ...,    997,    998,    999],
       [  1000,   1001,   1002, ...,   1997,   1998,   1999],
       [  2000,   2001,   2002, ...,   2997,   2998,   2999],
       ...,
       [997000, 997001, 997002, ..., 997997, 997998, 997999],
       [998000, 998001, 998002, ..., 998997, 998998, 998999],
       [999000, 999001, 999002, ..., 999997, 999998, 999999]])

In [54]:
from IPython.display import Image

In [55]:
np.savez_compressed('test2107.npz', p11)

In [56]:
np.save('test2108.npy', p11)

In [59]:
#Vektörler

In [60]:
v1 = np.array([1,2])
v2 = np.array([3,4])
#v3 = v1 + v2
v3 = np.add(v1, v2)
print('V3 =', v3)

V3 = [4 6]


In [61]:
a1 = np.array([5, 6, 8])
a2 = np.array([4, 7, 9])
print(np.multiply(a1, a2))

[20 42 72]


In [62]:
#Dot product

In [63]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

dotp = a1@a2
print("Dot product - ", dotp)

dotp2 = np.dot(a1, a2)
print("Dot product using np.dot", dotp2)

dotp3 = np.inner(a1, a2)
print("Dot product using np.inner", dotp3)

dotp4 = sum(np.multiply(a1, a2))
print("Dot product using np.multiply & sum", dotp4)

dotp5 = np.matmul(a1, a2)
print("Dot product using np.matmul", dotp)

dotp6 = 0
for i in range(len(a1)):
    dotp6 = dotp6 + a1[i]*a2[i]
print("Dot product using for loop", dotp6)


Dot product -  32
Dot product using np.dot 32
Dot product using np.inner 32
Dot product using np.multiply & sum 32
Dot product using np.matmul 32
Dot product using for loop 32


In [64]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3, v3))
length

9.539392014169456

In [65]:
#Normalizasyon


In [66]:
v1 = [2, 3]
length_v1 = np.sqrt(np.dot(v1, v1))
norm_v1 = v1 / length_v1
length_v1, norm_v1

(3.605551275463989, array([0.5547002 , 0.83205029]))

In [67]:
v1 = [2, 3]
norm_v1 = v1 / np.linalg.norm(v1)
norm_v1

array([0.5547002 , 0.83205029])

In [68]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
mat1 = np.random.randint(0, 5000, (10,10))

In [78]:
mat1

array([[3485,  699, 1659,   77, 2173, 4836, 1288, 4509, 3804, 3141],
       [4260, 4440, 3369, 2070, 4015, 4384, 4895, 3576, 2206, 1811],
       [ 481, 1116,  248, 2325, 1497, 3982, 2296,  108, 4550,  582],
       [ 913, 4648, 1119, 1702,  755,  762, 2949, 3297, 4672, 3549],
       [2550, 2946, 4989, 4018, 2371, 3588,   55, 3422, 1821, 3348],
       [3455, 1149,  509, 3700, 3637, 4746, 1075, 3509, 3186, 2352],
       [ 986,  272, 1763, 2851, 4168, 4245, 3552, 3486, 2643, 3961],
       [3662, 2895, 1676, 3887, 2260,  510, 2353,  522, 3346, 3527],
       [ 982, 1442, 1195, 2659, 3155, 3205, 2797, 3548, 3949, 2583],
       [2544,  272, 3429,  992, 3618, 3912,  666, 2701,  276, 1695]])

In [79]:
mat1[mat1 > 300]

array([3485,  699, 1659, 2173, 4836, 1288, 4509, 3804, 3141, 4260, 4440,
       3369, 2070, 4015, 4384, 4895, 3576, 2206, 1811,  481, 1116, 2325,
       1497, 3982, 2296, 4550,  582,  913, 4648, 1119, 1702,  755,  762,
       2949, 3297, 4672, 3549, 2550, 2946, 4989, 4018, 2371, 3588, 3422,
       1821, 3348, 3455, 1149,  509, 3700, 3637, 4746, 1075, 3509, 3186,
       2352,  986, 1763, 2851, 4168, 4245, 3552, 3486, 2643, 3961, 3662,
       2895, 1676, 3887, 2260,  510, 2353,  522, 3346, 3527,  982, 1442,
       1195, 2659, 3155, 3205, 2797, 3548, 3949, 2583, 2544, 3429,  992,
       3618, 3912,  666, 2701, 1695])

In [80]:
#Birim (Identity) Matris

In [85]:
I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [86]:
I = np.eye(9,5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
D = np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [90]:
#Üçgen (Triangular) Matris

In [91]:
M = np.random.randn(5, 5)
U = np.triu(M) #üst üçgen
L = np.tril(M) #alt üçgen

print(M)
print("\n")
print("Upper triangular matrix - \n", U)
print("\n")
print("Lower triangular matrix - \n", L)

[[-0.84141302 -0.44876222  0.49969895  0.02757126 -1.00946036]
 [-1.05203563 -0.3722272  -0.01583888 -0.18767454  0.98498982]
 [-0.69796276 -0.15413912  1.91995738 -0.60105435  0.25650628]
 [ 0.33972199 -0.10788814 -0.07823149  0.21473467 -0.57765095]
 [ 0.7280721   0.59485053 -1.205436   -0.32829728  1.93377393]]


Upper triangular matrix - 
 [[-0.84141302 -0.44876222  0.49969895  0.02757126 -1.00946036]
 [ 0.         -0.3722272  -0.01583888 -0.18767454  0.98498982]
 [ 0.          0.          1.91995738 -0.60105435  0.25650628]
 [ 0.          0.          0.          0.21473467 -0.57765095]
 [ 0.          0.          0.          0.          1.93377393]]


Lower triangular matrix - 
 [[-0.84141302  0.          0.          0.          0.        ]
 [-1.05203563 -0.3722272   0.          0.          0.        ]
 [-0.69796276 -0.15413912  1.91995738  0.          0.        ]
 [ 0.33972199 -0.10788814 -0.07823149  0.21473467  0.        ]
 [ 0.7280721   0.59485053 -1.205436   -0.32829728  1.933

In [92]:
M = np.array([[1,2,3], [4, -3, 6], [7, 8, 0]])
print("\n Matrix (M) ==> \n", M)

print("\nTranspose of M ==> \n", np.transpose(M))

#VEYA

print("\nTranspose of M ==> \n", M.T)


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]

Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [93]:
M = np.array([[1,2,3], [4, -3, 6], [7, 8, 0]])

print("\nDeterminant of M ==> ", np.linalg.det(M))


Determinant of M ==>  195.0


In [94]:
#Matrisin Kuvvetini Alma

In [95]:
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [96]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [97]:
M1*M1*M1

array([[  1,   8],
       [ 64, 125]])

In [98]:
np.linalg.matrix_power(M1, 3)


array([[ 57,  78],
       [156, 213]])

In [99]:
#Tensörler

In [100]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10, 20, 30], [40, 50, 60], [70, 80, 90]],
    [[100, 200, 300], [400, 500, 600], [700, 800, 900]],
])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [103]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]],
])
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [104]:
A = T1 + T2
#VEYA
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [105]:
S = T1 - T2
#VEYA
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [106]:
P = T1*T2
#VEYA
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [107]:
D = T1 / T2
#VEYA
np.divide(T1,T2)

C:\Users\ANILERMAN\AppData\Local\Temp\ipykernel_15600\133414315.py:1: RuntimeWarning: divide by zero encountered in true_divide
  D = T1 / T2
C:\Users\ANILERMAN\AppData\Local\Temp\ipykernel_15600\133414315.py:3: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(T1,T2)


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [108]:
import pandas as pd
import matplotlib.pyplot as plt
import math
import warnings
warnings.filterwarnings("ignore")

In [109]:
#Seriler

In [110]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [111]:
s1.dtype

dtype('int32')

In [112]:
s1.nbytes

28

In [113]:
s1.size

7

In [114]:
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [115]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [116]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.14581786, 0.77496278, 0.51597778, 0.52880376, 0.48563969,
        0.38960419, 0.64158702, 0.83236132, 0.60891678, 0.10985648]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.145818
 1    0.774963
 2    0.515978
 3    0.528804
 4    0.485640
 5    0.389604
 6    0.641587
 7    0.832361
 8    0.608917
 9    0.109856
 dtype: float64)

In [117]:
#Sözlükten Seri Oluşturma

In [118]:
dict1 = {'a1':10, 'a2':20, 'a3':30, 'a4':40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [119]:
pd.Series(99, index = [0,1,2,3,4,5])


0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [120]:
s

0    0.145818
1    0.774963
2    0.515978
3    0.528804
4    0.485640
5    0.389604
6    0.641587
7    0.832361
8    0.608917
9    0.109856
dtype: float64

In [121]:
s[:]

0    0.145818
1    0.774963
2    0.515978
3    0.528804
4    0.485640
5    0.389604
6    0.641587
7    0.832361
8    0.608917
9    0.109856
dtype: float64

In [122]:
s[-3:-1]

7    0.832361
8    0.608917
dtype: float64

In [123]:
#Serileri Birleştirme
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [124]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [125]:
s4 = s1.append(s3)

In [126]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [127]:
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [128]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [129]:
s4.drop('a4', inplace = True)

In [130]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [131]:
#ödev

In [134]:
abn = np.arange(0,200)

In [135]:
abn

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [136]:
abb = abn[abn % 2 == 0]
abb

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [137]:
abb.reshape(10,10)

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [162]:
def onesquarematris(ac,ab):
    uzn = np.zeros(ac*ab)
    uzn = uzn.reshape(ac,ab)
    el = ab-1
    ele = ac - 1
    for i in range(ac):
        for j in range(ab):
            if i == 0:
               uzn[i][j] = 1 
            if j == 0:
                uzn[i][j] = 1
            if j == el:
                uzn[i][j] = 1
            if i == ele:
                uzn[i][j] = 1
                    
    
    return uzn

onesquarematris(5,7)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])